version: "3.5"

services:
  wordpress:
    build: .
    restart: always
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: "db:3306"
      WORDPRESS_DB_NAME: "wordpress"
      WORDPRESS_DB_USER: "admin"
      WORDPRESS_DB_PASSWORD: "pass"
      WAIT_HOSTS: db:3306
      WAIT_SLEEP_INTERVAL: 5
    entrypoint: sh -c "/usr/local/bin/wait && docker-entrypoint.sh apache2-foreground"

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - "$PWD/.docker-compose/db-data:/var/lib/mysql"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "pass"
    user: "1000:50"
    command: --innodb-use-native-aio=0

networks:
  default:
    name: wordpress-net
